---
title: "pwrEWAS.data: Reference data accompanying pwrEWAS"
author: "Stefan Graw, Devin C. Koestler"
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('pwrEWAS.data')`"
#bibliography: minfi.bib
abstract: >
  This package provides reference data required for pwrEWAS. 
  pwrEWAS is a user-friendly tool to estimate power in EWAS as a function 
  of sample and effect size for two-group comparisons of DNAm 
  (e.g., case vs control, exposed vs non-exposed, etc.).
  Detailed description of in-/outputs, instructions and an example, 
  as well as interpretations of the example results are provided in 
  the following vignette.
vignette: >
  %\VignetteIndexEntry{pwrEWAS.data: Reference data accompanying pwrEWAS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::pdf_document:
    keep_tex: true
    number_sections: false
---

# Data

The following data sets were used to create the reference data. Therefore, for each tissue type CpG-specific means and variances were estimated ($\hat{\mu}_j =  1/N \sum_{i=1}^N \beta_{i,j}$ and $\sigma_j^2 = 1/(N-1) \sum_{i=1}^N (\beta_{i,j}-\hat{\mu}_j)^2$), where $\beta_{i,j}$ represents the methylation $\beta$-value for CpG j={1,.,J} in subject i={1,.,N}. 

\begin{table}[]
\hspace{-3cm}\begin{tabular}{llll}
\hline
Tissue Type              & Accession Number & Subjects within GSE-ID limited to & Reference                                 \\\hline\hline
Saliva                   & GSE92767         &                                   & (Hong et al., 2017)                       \\
Lymphoma                 & GSE42372         & disease state: non-HIV lymphoma   & (Matsunaga et al., 2014)                  \\
Placenta                 & GSE62733         & health state: Normal              & (Kawai et al., 2015)                      \\
Liver                    & GSE61258         & diseasestatus: Control            & (Horvath et al., 2014)                    \\
Colon                    & GSE77718         & disease state: Normal             & (McInnes et al., 2017)                    \\
Blood (Adults)           & GSE42861         & subject: Normal                   & (Kular et al., 2018; Y. Liu et al., 2013) \\
Blood (Children)         & GSE83334         & age: 5 years                      & (Urdinguio et al., 2016)                  \\
Blood (Newborns)         & GSE82273         &                                   & (Markunas et al., 2016)                   \\
Cord-blood (whole blood) & GSE69176         &                                   &                                           \\
Cord-blood (PBMC)        & GSE110128        & cord blood                        & (Langie et al., 2018)                     \\
Adult (PBMC)             & GSE67170         & disease state: control            & (Y. H. Zhang et al., 2018)                \\
Sperm                    & GSE114753        & control                           & (Jenkins et al., 2017)                    \\ \hline
\end{tabular}
\end{table}


