df = data.frame("Title" = NA, 
                "Decription" = NA, 
                "BiocVersion" = NA, 
                "Genome" = NA, 
                "SourceType" = NA, 
                "SourceUrl" = NA, 
                "SourceVersion" = NA, 
                "Species" = NA, 
                "TaxonomyId" = NA, 
                "Coordinate_1_based" = NA, 
                "DataProvider" = NA, 
                "Maintainer" = NA, 
                "RDataClass" = NA, 
                "DispatchClass" = NA, 
                "RDataPath" = NA, 
                "Tags" = NA, 
                "Notes" = NA)


df[1:12,] = matrix(c("Saliva", "Lymphoma", "Placenta", "Liver", "Colon", "Blood (Adults) - Peripheral Leukocytes", "Blood 5 year olds", "Blood newborns", "Cord-blood (whole blood)", "Cord-blood (PBMC)", "Adult (PBMC)", "Sperm",
                     paste("Genome-wide CpG-specific means and variance for ", c("Saliva", "Lymphoma", "Placenta", "Liver", "Colon", "Blood (Adults) - Peripheral Leukocytes", "Blood 5 year olds", "Blood newborns", "Cord-blood (whole blood)", "Cord-blood (PBMC)", "Adult (PBMC)", "Sperm"), sep = ""),
                     rep("3.9", 12),
                     rep(NA,12), # rep("HM450k", 12),
                     rep("TXT",12),
                     paste("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=", c("GSE92767", "GSE42372", "GSE62733", "GSE61258", "GSE77718", "GSE42861", "GSE83334", "GSE82273", "GSE69176", "GSE110128", "GSE67170", "GSE114753"), sep = ""),
                     rep(NA,12), # rep(format(Sys.time(), "%b %d %Y"),12),
                     rep("Homo sapiens",12),
                     rep(9606,12),
                     rep(NA,12),
                     rep("GEO",12),
                     rep("sgraw@kumc.edu",12),
                     rep(NA,12),
                     rep("Rda",12),
                     rep("path?",12),
                     rep(NA,12),
                     rep("HM450k",12)),
                   nrow = 12, ncol = 17, byrow = F
)

write.csv(df, file = "../extdata/metadata.csv", row.names=FALSE)
